spring.application.name=project
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/myproject?allowPublicKeyRetrieval=true&useSSL=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=MyS3cur3P@ss!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true
spring.security.oauth2.client.registration.google.client-id=492482174004-43lve4skodv324c50rk04aubgh4t7b42.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.web.resources.static-locations=classpath:/static/,file:./uploads/
logging.level.org.springframework.security=DEBUG
cloudinary.cloud-name=dqu6gauoj
cloudinary.api-key=526858866151778
cloudinary.api-secret=eYNTkHcwlV29uB1c11EElfeoaxI
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kien3031999@gmail.com
spring.mail.password=coxksferqmmwjceb
spring.mail.jndiName=http://localhost:8080
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

